Sudoux\EagleBundle\Entity\AssetRealEstateFull:
    type: entity
    table: asset_real_estate_full
    manyToOne:
      location:
        targetEntity: Sudoux\Cms\LocationBundle\Entity\Location
        cascade: ["persist", "remove"]
        joinColumns:
          location_id:
            referencedColumnName: id
        orphanRemoval: false
      borrower:
        targetEntity: Sudoux\EagleBundle\Entity\BorrowerFull
        inversedBy: asset_realestate
        cascade: ["persist"]
        joinColumns:
          borrower_id:
            referencedColumnName: id
        orphanRemoval: false
    indexes:
      market_value_idx:
        columns: [ market_value ]
      mortgage_amount_idx:
        columns: [ mortgage_amount ]
      date_aquired_idx:
        columns: [ date_aquired ]
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        market_value:
            type: float
            nullable: true
        mortgage_amount:
            type: float
            nullable: true
        original_cost:
            type: float
            nullable: true
        mortgage_payment:
            type: float
            nullable: true
        rent_gross_income:
            type: float
            nullable: true
        ins_tax_exp:
            type: float
            nullable: true
        rent_net_income:
            type: float
            nullable: true
        date_aquired:
            type: datetime
            nullable: true
        status:
            type: integer
            nullable: true
    lifecycleCallbacks: {  }