Sudoux\EagleBundle\Entity\AssetAccountFull:
    type: entity
    table: asset_account_full
    manyToOne:
      borrower:
        targetEntity: Sudoux\EagleBundle\Entity\BorrowerFull
        inversedBy: asset_account
        cascade: ["persist"]
        joinColumns:
          borrower_id:
            referencedColumnName: id
        orphanRemoval: false
    indexes:
      institution_name_idx:
        columns: [ institution_name ]
      account_number_idx:
        columns: [ account_number ]
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        institution_name:
            type: string
            length: 255
            nullable: true
        type:
            type: smallint
            nullable: true
        account_number:
            type: string
            length: 255
            nullable: true
        balance:
            type: float
            nullable: true
    lifecycleCallbacks: {  }
