Sudoux\EagleBundle\Entity\EagleLoanDocument:
    type: entity
    table: eagle_loan_document
    repositoryClass: Sudoux\MortgageBundle\Entity\EagleLoanDocumentRepository
    manyToOne:
      file:
        targetEntity: Sudoux\Cms\FileBundle\Entity\File
        cascade: ["persist", "remove"]
        mappedBy: null
        inversedBy: null
        joinColumns:
          file_id:
            referencedColumnName: id
        orphanRemoval: false
      type:
        targetEntity: Sudoux\Cms\TaxonomyBundle\Entity\Taxonomy
        cascade: {  }
        mappedBy: null
        inversedBy: null
        joinColumns:
          taxonomy_id:
            onDelete: "SET NULL"
            referencedColumnName: id
        orphanRemoval: false
    manyToMany:
      loan:
        targetEntity: Sudoux\EagleBundle\Entity\EagleLoanApplication
        mappedBy: document
    indexes:
      losid_idx:
        columns: [ los_id ]
      name_idx:
        columns: [ name ]
      created_idx:
        columns: [ created ]
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: '255'
            nullable: true
        extension:
            type: string
            length: '20'
            nullable: true
        status:
            type: integer
            nullable: true
        required:
            type: boolean
            nullable: true
        los_id:
            type: string
            length: '255'
            nullable: true
        los_status:
            type: smallint
            nullable: true
        created:
            type: datetime
    lifecycleCallbacks: {  }