parameters:
#    sudoux_eagle.example.class: Sudoux\EagleBundle\Example

services:
#    sudoux_eagle.example:
#        class: %sudoux_eagle.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
