parameters:
#    sudoux_mortgage_api.example.class: Sudoux\MortgageApiBundle\Example

services:
#    sudoux_mortgage_api.example:
#        class: %sudoux_mortgage_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
