<?php

namespace Sudoux\EagleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BorrowerFullRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BorrowerFullRepository extends EntityRepository
{
}
