<?php

namespace Sudoux\EagleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LoanDocumentFullRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoanDocumentFullRepository extends EntityRepository
{
}
